# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source ‘https://github.com/CocoaPods/Specs.git’

target 'RAC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RAC
  pod 'ReactiveObjC', '~>3.0'

end
